channels:
  - conda-forge
  - defaults

# Compatibility chart: https://stackoverflow.com/questions/62690377/tensorflow-compatibility-with-keras
dependencies:
  - python=3.6
  - ipykernel=5.5.5
  - pip=21.*
  - pip:
    - tensorflow==1.7.0
    - keras==2.1.6
    - Keras-Applications==1.0.8
    - h5py==2.10.0
    - numpy==1.14.3
    - matplotlib==2.2.2
    - scipy==1.0.1
    - scikit-image==0.14.0
    - opencv-python==3.4.0.14
