channels:
  - conda-forge
  - defaults

# Compatibility chart: https://stackoverflow.com/questions/62690377/tensorflow-compatibility-with-keras
dependencies:
  - python=3.6
  - ipykernel=5.5.5
  - pip=21.*
  - pip:
    - tensorflow==1.15.5
    - keras==2.3.1
    - matplotlib==3.1.3
    - scikit-image==0.16.2
    - opencv-python==3.4.8.29
